blank_issues_enabled: true
contact_links:
  - name: Start a discussion about a potential improvement to selene or ask a question
    url: https://github.com/cmagovuk/selene-core/discussions/new
    about: Ask a question or request support for using KEDA
