name: CI-build-docs

on:
  push:
    branches: [ master, documentation ]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Token
        uses: cmagovuk/github-app-installation-token-action@v2
        id: installationToken
        with: 
          appId: ${{ secrets.TALOS_V2_APP_ID }}
          installationId: ${{secrets.TALOS_V2_INSTALLATION_ID }}
          privateKey: ${{ secrets.TALOS_V2_PRIVATE_KEY }}
      - name: Setup git
        run: |
          git config --global url."https://x-access-token:${{ steps.installationToken.outputs.token }}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://x-access-token:${{ steps.installationToken.outputs.token }}@github.com/".insteadOf "git@github.com:"
      - name: Install pandoc
        run: |
          sudo apt-get install pandoc
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          sudo apt-get install -y graphviz graphviz-dev
          python -m pip install -r docs/requirements.txt
      # NOTE could use https://github.com/quarto-dev/quarto-actions
      # TODO is there a way to not pin quarto?
      - name: Install quarto
        run: |
          wget https://github.com/quarto-dev/quarto-cli/releases/download/v0.9.345/quarto-0.9.345-linux-amd64.deb
          sudo dpkg -i quarto-0.9.345-linux-amd64.deb
      - name: Pull submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Make documentation HTML
        run: |
          cd docs
          make html
      # NOTE could use https://github.com/peaceiris/actions-gh-pages
      - name: Commit documentation changes
        run: |
          rm -r ~/.gitconfig
          git config --global user.email "you@example.com"
          git config --global user.name "GithubAction"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git add .
          git commit -m "Update documentation"
          git push -f origin HEAD:docs
