name: CI-build-docs

on:
  push:
    branches: [ master, dayalstrub-cma-patch-1 ]
  pull_request: # no filters on pull requests

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pandoc
        run: |
          sudo apt-get install pandoc
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          python -m pip install .
          cd docs
          make requirements
      - name: Make documentation HTML
        run: |
          cd docs
          make html
      # NOTE could use https://github.com/peaceiris/actions-gh-pages
      - name: Commit documentation changes
        if: github.event_name == 'push'
#         run: |
#           rm -r ~/.gitconfig
#           git config --global user.email "you@example.com"
#           git config --global user.name "GithubAction"
#           git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
#           git add -f .
#           git commit -m "Update documentation"
#           git push -f origin HEAD:docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: docs
