name: CI-run-tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push to master or pull request events
  push:
    branches: [ master ]
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PACKAGE: "selene"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Set up python using default action
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # Install / upgrade tox etc for testing
      - name: Install testing dependencies
        run: |
          python -m pip install --upgrade pip black tox
      # Run tests 
      - name: Test selene
        run: |
          cd ${{ env.PACKAGE }}
          tox
